"""add_organisations_table_v2

Revision ID: 843b6cacbbcc
Revises: c64f9caead9f
Create Date: 2026-05-14 11:01:34.614032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843b6cacbbcc'
down_revision: Union[str, Sequence[str], None] = 'c64f9caead9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
